import React, { useState } from 'react';
import { Target, Loader2, CheckCircle, XCircle } from 'lucide-react';
import { aiJson } from '../../services/ai';
import { db } from '../../utils/storage';

export default function TestTab({ profile, vlsiProgress, setVlsiProgress }) {
  const [test, setTest] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);

  const generate = async () => {
    setGenerating(true);
    const prompt = `Generate a 5-question multiple choice test for VLSI Phase: ${profile.vlsiPhase}.
    Include:
    - 2 questions from new topics (Phase ${profile.vlsiPhase}, Day ${profile.vlsiDay})
    - 2 revision questions from ALL previous topics
    - 1 challenge question mixing multiple topics
    
    Return a JSON object:
    {
      "questions": [
        {
          "id": 1,
          "text": "Question text...",
          "type": "🆕 This week" | "🔁 Revision" | "🔥 Challenge",
          "options": ["A", "B", "C", "D"],
          "correctIndex": 0,
          "explanation": "Why A is correct"
        }
      ]
    }`;
    
    const sys = "You are a senior VLSI professor. Output valid JSON only.";
    const result = await aiJson(prompt, sys);
    
    if (result && result.questions) {
      setTest(result.questions);
      setAnswers({});
      setSubmitted(false);
    }
    setGenerating(false);
  };

  const submit = async () => {
    let s = 0;
    test.forEach((q, i) => {
      if (answers[i] === q.correctIndex) s += 1;
    });
    setScore(s);
    setSubmitted(true);
    
    const newProgress = { ...vlsiProgress };
    if (!newProgress.testScores) newProgress.testScores = [];
    newProgress.testScores.push({ date: new Date().toISOString(), score: s, total: 5 });
    
    setVlsiProgress(newProgress);
    await db.set('vlsiProgress', newProgress);
  };

  if (!test && !generating) {
    return (
      <div className="glass-card" style={{ padding: '30px 20px', textAlign: 'center' }}>
        <Target size={48} color="#ef4444" style={{ margin: '0 auto 16px' }} />
        <h3 style={{ fontSize: '18px', marginBottom: '8px' }}>Weekly Cumulative Test</h3>
        <p style={{ fontSize: '14px', color: 'var(--color-text-secondary)', marginBottom: '24px' }}>
          5 questions generated by Gemini (2 New, 2 Revision, 1 Challenge). Your score adjusts future lesson difficulty.
        </p>
        <button onClick={generate} style={{ padding: '12px 24px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 600 }}>Generate Weekly Test</button>
      </div>
    );
  }

  if (generating) {
    return (
      <div className="glass-card" style={{ padding: '40px 20px', textAlign: 'center' }}>
        <Loader2 size={40} color="#ef4444" className="animate-spin" style={{ margin: '0 auto 16px' }} />
        <p style={{ color: 'var(--color-text-secondary)' }}>Gemini is writing your test...</p>
      </div>
    );
  }

  return (
    <div className="glass-card" style={{ padding: '20px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <h3 style={{ fontSize: '18px' }}>Weekly Assessment</h3>
        {submitted && <span style={{ fontSize: '20px', fontWeight: 700, color: score >= 4 ? '#10b981' : (score >= 3 ? '#f59e0b' : '#ef4444') }}>{score} / 5</span>}
      </div>

      {test.map((q, i) => (
        <div key={i} style={{ marginBottom: '24px', paddingBottom: '16px', borderBottom: i < 4 ? '1px solid var(--color-border-secondary)' : 'none' }}>
          <div style={{ display: 'flex', gap: '8px', marginBottom: '8px' }}>
            <span style={{ fontSize: '10px', padding: '2px 6px', background: 'var(--color-bg-tertiary)', borderRadius: '4px', color: 'var(--color-text-secondary)' }}>Q{i+1}</span>
            <span style={{ fontSize: '10px', padding: '2px 6px', background: q.type.includes('Challenge') ? '#ef444420' : 'var(--color-accent-vlsi)20', color: q.type.includes('Challenge') ? '#ef4444' : 'var(--color-accent-vlsi)', borderRadius: '4px' }}>{q.type}</span>
          </div>
          <p style={{ fontSize: '14px', marginBottom: '12px', lineHeight: 1.5 }}>{q.text}</p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {q.options.map((opt, optIdx) => {
              const isSelected = answers[i] === optIdx;
              const isCorrect = q.correctIndex === optIdx;
              
              let bg = 'var(--color-bg-secondary)';
              let border = '1px solid var(--color-border-primary)';
              
              if (submitted) {
                if (isCorrect) { bg = '#10b98120'; border = '1px solid #10b981'; }
                else if (isSelected) { bg = '#ef444420'; border = '1px solid #ef4444'; }
              } else if (isSelected) {
                border = '1px solid var(--color-accent-vlsi)';
              }

              return (
                <button 
                  key={optIdx}
                  onClick={() => !submitted && setAnswers(p => ({ ...p, [i]: optIdx }))}
                  style={{ textAlign: 'left', padding: '12px', borderRadius: '8px', background: bg, border, color: 'white', fontSize: '13px', display: 'flex', alignItems: 'flex-start', gap: '12px', cursor: submitted ? 'default' : 'pointer' }}
                >
                  <div style={{ width: '20px', height: '20px', borderRadius: '50%', border: '1px solid var(--color-text-tertiary)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, background: isSelected ? 'var(--color-accent-vlsi)' : 'transparent' }}>
                    {submitted && isCorrect && <CheckCircle size={14} color="#10b981" />}
                    {submitted && isSelected && !isCorrect && <XCircle size={14} color="#ef4444" />}
                  </div>
                  {opt}
                </button>
              );
            })}
          </div>
          
          {submitted && (
            <div style={{ marginTop: '12px', padding: '12px', background: 'var(--color-bg-tertiary)', borderRadius: '8px' }}>
              <p style={{ fontSize: '12px', color: 'var(--color-text-secondary)', lineHeight: 1.5 }}><strong style={{ color: 'white' }}>Explanation:</strong> {q.explanation}</p>
            </div>
          )}
        </div>
      ))}

      {!submitted ? (
        <button 
          onClick={submit}
          disabled={Object.keys(answers).length < 5}
          style={{ width: '100%', padding: '14px', background: Object.keys(answers).length === 5 ? '#ef4444' : 'var(--color-bg-tertiary)', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 600 }}
        >
          Submit Test
        </button>
      ) : (
        <button 
          onClick={() => setTest(null)}
          style={{ width: '100%', padding: '14px', background: 'transparent', color: 'white', border: '1px solid var(--color-border-primary)', borderRadius: '8px' }}
        >
          Return to Dashboard
        </button>
      )}
    </div>
  );
}
